# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft
minecraft_version=26.2.0
minecraft_version_range=[26.2.0,)
# https://projects.neoforged.net/neoforged/neogradle
neogradle_version=7.1.38

# https://neoforged.net/
neoforge_version=26.2.0.12-beta
neoforge_version_range=[26.2.0.12-beta,)

# Mod Properties
mod_id=starry_skies
mod_version=5.0.0+26.1-neoforge
mod_name=Starry Skies
mod_group_id=de.dafuqs
archives_base_name=StarrySkies
mod_license=GPL-3.0
mod_authors=DaFuqs
mod_description=Extensive 'planetoids' style world generator
issue_tracker_url=https://github.com/DaFuqs/StarrySkies/issues
display_url=https://github.com/DaFuqs/StarrySkies