# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=4.3.0+26.2
maven_group=de.dafuqs
archives_base_name = StarrySkies

# Dependencies
fabric_api_version=0.153.0+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.0-beta.4

# https://github.com/kyrptonaught/customportalapi
custom_portal_api_version=0.0.1-beta69-26.1